### ISSUE TITLE
你好，我想问一下您的项目可以执行吗

### ISSUE THREAD

**Issue by Hi-hujiajia** [songquanpeng/online-code-editor#1]

**Comment by Hi-hujiajia** [comment]
就是我在您的项目里写代码，我输入print（“hello”），点击submit 可以输出hello 吗

**Comment by songquanpeng** [comment]
不好意思这么晚才回复（因为我之前取消 watch 了自己的仓库，没想到自己收不到 issue 通知）。

该项目只是一个简陋的在线代码编辑器，并不能运行代码。

**Comment by Hi-hujiajia** [comment]
非常感谢您的回复呢，功能蛮好的，我是想做一个网页编辑器，带编译的，我想问一下，您的编辑器是富文本编辑的吗，我想请教一些技术问题，你的技术路线大概是什么样子的呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "songquanpeng/online-code-editor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月17日(星期二) 晚上9:21
收件人:&nbsp;"songquanpeng/online-code-editor"<online-code-editor@noreply.github.com&gt;;
抄送:&nbsp;"那改改"<1161520694@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [songquanpeng/online-code-editor] 你好，我想问一下您的项目可以执行吗 (#1)





 
不好意思这么晚才回复（因为我之前取消 watch 了自己的仓库，没想到自己收不到 issue 通知）。
 
该项目只是一个简陋的在线代码编辑器，并不能运行代码。

**Comment by songquanpeng** [comment]
这个并不是富文本编辑器，只是单纯的代码编辑器（而且这个仅仅是个玩具项目）。像你所描述的那种可以编译运行的，我建议你可以去参考一下一些开源的 OJ 系统。
